Add classes and @media q. for RWD
Varenthein/wdp-1902-03 pull request #10
Opened 2019-03-02 21:04 UTC by Shoulao

**Cel:**

- dodanie RWD dla sekcji **latest-post**
          - dla **mobile**: 1 element/wiersz,
          - dla **tablet**: 2 elementy/wiersz,

**Rozwiązanie:**

- dodanie klas pomocniczych bootstrap dla elementów html
- dodanie @media dla poszczególnych widoków i modyfikacja szerokości w zależności od res.
- **zmieniłem trochę założenie:**
          - dla **mobile**: 1 element w portrait i landscape
          - dla **tablets**: 2 elementy w portrait i 3 elementy w landscape (lepiej to wygląda, mniej 
          pustego miejsca) oraz wyśrodkowanie w przypadku jednego elementu w ostatnim wierszu
          - dodałem `margin: 0 10 px` dla **mobile**, lepiej wygląda
**Efekt:**

- testowane - działa, dobrze wygląda

2019-03-07 19:45 UTC, stepek commented
Please fix conflicts

2019-03-09 18:06 UTC, xkxd requested changes

2019-03-09 18:06 UTC, xkxd commented on src/sass/components/_post-box.scss
> +        .col-sm-12 {
ponownie - dlaczego potrzebujesz tak dużego zagniezdzenia?
w tym wypadku z uwagi na specificity w zupełności wystarczyłby selektor `.section--blog-posts .col-sm-12`, analogicznie w przypadku `col-md-6`

2019-03-14 23:48 UTC, Shoulao commented on src/sass/components/_post-box.scss
> +        .col-sm-12 {
Poprawione :)

2019-03-15 07:19 UTC, merged