WDP190203-11
Varenthein/wdp-1902-03 pull request #11
Opened 2019-03-04 11:48 UTC by AleksandraDworak

Strona sypie się w trybach responsive. Klient nie ma designów RWD, więc trzeba zrobić na własną rękę.
Ten task dotyczy menu głównego (wyszukiwanie i "Home", etc.)
Na tabletach wyszukiwanie ma być pod menu, a na mniejszych ekranach ma być wyszukiwanie i obok niego ikona mobilnego menu, które po rozwinięciu ma pokazywać dropdown przykrywający treść strony.

Rozwiązanie:
Dla tabletów menu zastosowano szersze menu - żeby wszystko się mieściło - zgodnie z zadaniem wyszukiwanie jest pod menu

dla mniejszych rozdzielczości menu jest ukrywane - dodano przycisk pokazujący się tylko dla tych rozdzielczości rozwija menu (dodano skrypt obsługujący to zdarzenie).

2019-03-07 19:45 UTC, stepek commented
Please fix conflicts

2019-03-09 18:09 UTC, xkxd requested changes
cały plik ze stylami wygląda jakby został wcięty o kilka spacji w efekcie czego masz 
a) bardzo duzo zmian, mimo iż kod nie został zmieniony
b) konflikty

2019-03-09 18:09 UTC, xkxd commented on src/sass/components/_header.scss
> +  header {
czy te wcięcia są tu potrzebne?

2019-03-09 18:09 UTC, xkxd commented on src/sass/components/_header.scss
> +            color: #ffffff;
kolor do zmiennej

2019-03-09 18:09 UTC, xkxd commented on src/sass/components/_header.scss
> +          color: #ffffff;
kolor do zmiennej

2019-03-14 04:58 UTC, xkxd approved these changes

2019-03-15 07:20 UTC, merged