Update top menu select (WDP190203-10)
Varenthein/wdp-1902-03 pull request #14
Opened 2019-03-05 16:23 UTC by MarcinAleksanderek

Created PR to correct repository

2019-03-07 18:54 UTC, stepek approved these changes

2019-03-09 18:14 UTC, xkxd requested changes
plik `src/css/style.css` prawdopodobnie nie powinien się tu znaleźć z uwagi na jego rozmiar.

2019-03-09 18:14 UTC, xkxd commented on src/sass/components/_header.scss
> +            nav ul li:hover > ul li a {
dodaj do (chociaż części) poszczególnych elementów klasy i ostyluj je bezpośrednio. tworzenie tak skomplikowanych selektorów bardzo utrudnia pozniejsze wprowadzanie zmian.

2019-03-10 14:18 UTC, MarcinAleksanderek commented
Zmieniłem ostylowanie na klasy

2019-03-12 19:36 UTC, AleksandraKoelmer approved these changes

2019-03-12 19:36 UTC, AleksandraDworak commented on src/sass/components/_header.scss
> +            nav .topmenu li:hover > .topmenu li a {
myślę że dałoby się utworzyć prostszy selektor

2019-03-14 04:59 UTC, xkxd approved these changes

2019-03-14 05:00 UTC, xkxd commented
nadal nie jestem przekonany co do obecnosci pliku `style.css` @stepek @Varenthein co wy na to?

2019-03-15 07:23 UTC, Varenthein commented
> nadal nie jestem przekonany co do obecnosci pliku `style.css` @stepek @Varenthein co wy na to?

Zgadzam się. Nie ma potrzeby jego obecności tutaj.

2019-03-16 12:09 UTC, MarcinAleksanderek commented
Hej, usunąłem CSS'a.

2019-03-16 12:58 UTC, Varenthein commented
Rozwiąż proszę konflikty

2019-03-16 21:43 UTC, MarcinAleksanderek commented
Konflikty rozwiązane

2019-03-17 13:49 UTC, merged