make link from "feature box" elements and add hover efect
Varenthein/wdp-1902-03 pull request #17
Opened 2019-03-06 20:48 UTC by bsopecki

Cel:
- przerobienie elementów "features" na linki i nadanie im stanu hover

Rozwiązanie:
- zawartość elementów "feature-box" wrzuciłem w tag <a></a>
- nadałem mu odpowiedni wygląd w stanie hover
- wyrzuciłem nadany na sztywno wygląd pierwszego elementu.

2019-03-06 20:58 UTC, bsopecki commented
Mam prośbę: 

Po rozwiązaniu konfliktów testy nie przechodzą. Z loga widzę, że chodzi o jakieś domknięcie tylko, że żadnego nie usuwałem i tego jestem pewien. Wskażcie mi proszę linię w , której go brakuje.

2019-03-07 18:04 UTC, stepek requested changes

2019-03-07 18:04 UTC, stepek commented on src/partials/30_section-features.html
> +          </a>
missing closing tags

2019-03-07 21:32 UTC, bsopecki commented
Zamykam ten Pull Request.

2019-03-07 21:32 UTC, closed without merging