WDP190203-21
Varenthein/wdp-1902-03 pull request #19
Opened 2019-03-07 21:31 UTC by AleksandraDworak

Zadanie: Jako pierwszą sekcję na stronie należy dodać sekcję "Promowane" według designu:

https://uploads.kodilla.com/bootcamp/wdp/group-project-01/section-featured.png

 Ten task dotyczy tylko napisania HTML i CSS.

2019-03-09 18:25 UTC, xkxd requested changes

2019-03-09 18:25 UTC, xkxd commented on src/sass/components/_featured.scss
> +  #cart-btn {
uzywaj klas zamiast id do stylowania

2019-03-09 18:25 UTC, xkxd commented on src/sass/components/_featured.scss
> +      width: 0px;
`0`, bez jednostek

2019-03-10 20:22 UTC, AleksandraDworak commented on src/sass/components/_featured.scss
> +  #cart-btn {
zmienione

2019-03-10 20:22 UTC, AleksandraDworak commented on src/sass/components/_featured.scss
> +      width: 0px;
zmienione

2019-03-15 07:22 UTC, merged