Wdp190203 29
Varenthein/wdp-1902-03 pull request #27
Opened 2019-03-16 16:11 UTC by AleksandraDworak

Zadanie:
Zadaniem jest dodanie na stronie sekcji z markami według designu:
https://uploads.kodilla.com/bootcamp/wdp/group-project-01/section-brands.png
 W tym tasku do zrobienia jest tylko HTML i CSS.
Obrazki z logotypami marek nie są linkami.
Rozwiązanie:
Dodałam plik .html i .scss dla nowej sekcji, podłączyłam ją do index.html i style.scss, dodałam grafiki do folderu images.

Dodatkowe info:
Klasy elementów są ponazywane już pod task z karuzelą dla ułatwienia.
W plilku .scss jest fragment kodu który @MarcinAleksanderek powinien usunąć.
Przy realizacji karuzeli trzeba będzie zmienić domyślne style przycisków previous i next na te, które utworzyłam.

2019-03-16 21:54 UTC, Shoulao requested changes
Literówki w kodzie

2019-03-16 21:54 UTC, Shoulao commented on src/sass/_variables.scss
> +$brans-border-color: #e1e1e1;
literówka w kodzie, chyba chodziło o `brands` :)

2019-03-16 21:54 UTC, Shoulao commented on src/sass/components/_brands.scss
> +  border: 1px solid $brans-border-color;
literówka tutaj też, zgodnie z nazwą

2019-03-16 21:54 UTC, Shoulao commented on src/sass/components/_brands.scss
> +  border: 1px solid $brans-border-color;
i tutaj :)

2019-03-17 08:34 UTC, xkxd approved these changes

2019-03-17 08:34 UTC, xkxd commented on src/sass/components/_brands.scss
> +#carousel-cell1,
zamiast `id` moglabys uzyc `:first-of-type`/`:last-of-type`

2019-03-17 18:17 UTC, Shoulao approved these changes

2019-03-17 21:00 UTC, bsopecki approved these changes

2019-03-19 19:19 UTC, stepek approved these changes

2019-03-19 21:44 UTC, Varenthein commented
Rozwiąż proszę konflikt

2019-03-20 08:32 UTC, merged