Wdp190203-30
Varenthein/wdp-1902-03 pull request #28
Opened 2019-03-17 01:47 UTC by MarcinAleksanderek

Dodany skrypt, zaimportowany w index.html

2019-03-17 01:56 UTC, MarcinAleksanderek commented
Dodałem plik JS'a do inicjalizowania karuzeli oraz zmiany ilości skrolowanych elementów. Zaimportowałem plik w html.

2019-03-17 08:36 UTC, xkxd commented
czesc z tego kodu wyglada jakby była powielona względem https://github.com/Varenthein/wdp-1902-03/pull/26 - jak mają się do siebie oba PRy?

2019-03-17 10:24 UTC, MarcinAleksanderek commented
Hej, w całym projekcie kortzystamy z 5-6 karuzel. Ja chętnie wrzuciłbym wszystkie w jeden JS, ale niestety zanim nastąpi merge to blokuje pracę. W nadchodzącym tygodniu gdzie będziemy wymyślać nowe zadania zrobiłbym Code Review i połączył wszystko w jedną całość.

2019-03-19 22:40 UTC, Shoulao requested changes

2019-03-19 22:40 UTC, Shoulao commented on src/sass/components/_product-box.scss
> +
`flickity-viewport i flickity-page-dots` są umieszczone w globalnym zakresie. Jak zmergujemy ten zapis z master to posypią się style w innych miejscach gdzie są **dotsy**. Muszą być wpisane pod jakiś element konkretny

2019-03-24 10:54 UTC, MarcinAleksanderek commented
Przerzuciłem te style do odpowiedniej sekcji. Rozwiązuję konflikty

2019-03-24 16:13 UTC, Shoulao approved these changes

2019-03-24 22:24 UTC, merged