Wdp190203-20
Varenthein/wdp-1902-03 pull request #39
Opened 2019-03-24 23:24 UTC by MarcinAleksanderek

Dodałem karuzelę do bloga.

2019-03-25 15:24 UTC, Shoulao requested changes

2019-03-25 15:24 UTC, Shoulao commented on src/scripts/app.js
> +    e.originalTarget.classList.add('full');
Masz aktualnego mastera? We wcześniejszym PR też pisałeś `e.originalTarget` i poprawiałeś to - to typowo dla Mozilli jest. [Chodzi o ten task](https://github.com/Varenthein/wdp-1902-03/pull/23)

2019-03-25 15:24 UTC, Shoulao commented on src/scripts/app.js
> +Array.from(document.querySelectorAll('.stars')).forEach(function(a) {
To też poprawiałeś w [TASKU](https://github.com/Varenthein/wdp-1902-03/pull/23).

Zaciągnij sobie aktualnego mastera, bo chyba masz mastera, który jest nieaktualny i wyskoczy Ci pełno konfliktów.

2019-03-25 15:24 UTC, Shoulao commented on src/scripts/app.js
> +    console.log(e);
@stepek też zwracał uwagę na usunnięcie tego loga :)

2019-03-26 06:19 UTC, stepek approved these changes

2019-03-26 12:56 UTC, Shoulao approved these changes

2019-03-26 21:01 UTC, Varenthein commented
`20\src\sass\style.scss:108:17: Undefined variable.
    background: $flkty-bg-color;
                ^^^^^^^^^^^^^^^
  src\sass\components\_post-box.scss 108:17  @import
  stdin 18:9                                 root stylesheet

2019-03-26 21:39 UTC, MarcinAleksanderek commented
$flkty-bg-color - poszło z commitem Update_Variables.scss
https://github.com/Varenthein/wdp-1902-03/commit/ac2e6c90e6cef7e21229c32428e28269104614fb

2019-03-26 21:47 UTC, MarcinAleksanderek commented
rozwiązałem też konflikty

2019-03-26 21:48 UTC, merged