Update _variables.scss
Varenthein/wdp-1902-03 pull request #40
Opened 2019-03-24 23:35 UTC by MarcinAleksanderek

2019-03-25 14:11 UTC, bsopecki requested changes

2019-03-25 14:11 UTC, bsopecki commented on src/sass/_variables.scss
> +$flkty-bg-color: white;
ten sposób deklarowania kolorów to jedna ze złych praktyk. Popraw na prawidłowy.

2019-03-25 17:15 UTC, bsopecki approved these changes

2019-03-25 17:16 UTC, bsopecki commented
rozwiąż konflikt i po sprawie :)

2019-03-25 17:27 UTC, MarcinAleksanderek commented
rozwiązany ;)

2019-03-26 06:41 UTC, stepek approved these changes

2019-03-26 20:58 UTC, merged