Add script and styles for buttons in Product box
Varenthein/wdp-1902-03 pull request #7
Opened 2019-03-02 10:50 UTC by AleksandraDworak

Problem: 
Brak ostylowanych stanów "ulubiony" oraz "dodany do porównania". Te stany mogą być dodane na stałe poprzez dodanie klasy "active" na buttonie.

Rozwiązanie:
Utworzono skrypt productBox.js obsługujący dodawanie klasy -active na zdarzenie kliknięcia w przycisk + dodano style dla tej klasy.

Dodatkowo:
-zamieniono znaleziony kod hex koloru na zmienną z pliku variables

2019-03-03 14:24 UTC, xkxd commented on src/sass/components/_button.scss
> +  color: #ffffff;
kolor mozemy przypisać do zmiennej

2019-03-03 14:24 UTC, xkxd commented on src/scripts/ProductBox.js
> +  this.classList.toggle('btn-outline-active');
użyj `event.target/event.currentTarget`

2019-03-03 14:24 UTC, xkxd requested changes

2019-03-03 14:24 UTC, xkxd commented on src/scripts/ProductBox.js
> +  this.classList.toggle('btn-outline-active');
użyj `event.target/event.currentTarget`

2019-03-04 12:17 UTC, AleksandraDworak commented on src/sass/components/_button.scss
> +  color: #ffffff;
przypisane. Sprawdziłam i zmieniłam od razu w całym pliku _button

2019-03-04 12:17 UTC, AleksandraDworak commented on src/scripts/ProductBox.js
> +  this.classList.toggle('btn-outline-active');
poprawione zgodnie z uwagą

2019-03-06 20:23 UTC, xkxd approved these changes

2019-03-06 20:24 UTC, xkxd commented
rozwiąż konflikty i bedzie okej.

2019-03-07 19:46 UTC, stepek approved these changes

2019-03-09 17:56 UTC, merged